/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo_Prestamos;

import Modulo_Estudiante.ExcepcionDatosIncorrectos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Wilson Xicará
 */
public class VerListadoPaquetes extends javax.swing.JDialog {
    private Connection conexion;
    private boolean hacerVisible;
    private ArrayList<Integer> listaIDPaquetes;
    private TableRowSorter filtroTabla;
    private int indexPaqueteEditado;
    /**
     * Creates new form VerListadoPaquetes
     */
    public VerListadoPaquetes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public VerListadoPaquetes(java.awt.Frame parent, Connection conexion) {
        super(parent, true);
        initComponents();
        this.conexion = conexion;
        hacerVisible = true;
        
        // Obtengo la información de todos los Paquetes de libros guardados en la Base de Datos
        try {
            ResultSet cConsulta = conexion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY)
                    .executeQuery("SELECT PaqueteLibro.*, COUNT(Libro.PaqueteLibro_Id) cantidadLibros FROM PaqueteLibro "
                    + "INNER JOIN Libro ON PaqueteLibro.Id = Libro.PaqueteLibro_Id "
                    + "WHERE Libro.Estado != '6' "
                    + "GROUP BY PaqueteLibro_Id");
            listaIDPaquetes = new ArrayList<>();
            int contador = 0;
            DefaultTableModel modelPaquetes = (DefaultTableModel)tabla_paquetes.getModel();
            while(cConsulta.next()) {
                listaIDPaquetes.add(cConsulta.getInt("Id"));
                modelPaquetes.addRow(new String[]{
                    ""+(++contador),
                    cConsulta.getString("Codigo"),
                    cConsulta.getString("Descripcion")==null ? "<Sin especificar>" : cConsulta.getString("Descripcion"),
                    ""+cConsulta.getInt("cantidadLibros")
                });
            }
            // Otras configuraciones importantes
            filtroTabla = new TableRowSorter(tabla_paquetes.getModel()); // Objeto que permite filtrar filas de la Tabla
            tabla_paquetes.setShowHorizontalLines(true);  // Para mostrar los bordes de las celdas de la tabla
            tabla_paquetes.setShowVerticalLines(true);
            tabla_detalle_libros.setShowHorizontalLines(true);  // Para mostrar los bordes de las celdas de la tabla
            tabla_detalle_libros.setShowVerticalLines(true);
            panel_descripcion_paquete.setVisible(false);
            panel_nuevo_libro.setVisible(false);
            this.setLocationRelativeTo(null);   // Para centrar esta ventana sobre la pantalla
        } catch (SQLException ex) {
            hacerVisible = false;
            JOptionPane.showMessageDialog(this, "No se puede extraer alguno de los registros.\n\nDescripción:\n"+ex.getMessage(), "Error en conexión", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VerListadoPaquetes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_paquetes = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        filtrar_por = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        valor_a_filtrar = new javax.swing.JTextField();
        editar_paquete = new javax.swing.JButton();
        agregar_libro_a_paquete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_detalle_libros = new javax.swing.JTable();
        panel_descripcion_paquete = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        codigo_paquete = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion_paquete = new javax.swing.JTextArea();
        guardar_descripcion_de_paquete = new javax.swing.JButton();
        panel_nuevo_libro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigo_libro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre_libro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        autor_libro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editorial_libro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        estado_libro = new javax.swing.JComboBox<>();
        agregar_libro = new javax.swing.JButton();
        cancelar_edicion_libro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paquetes de Libros creados");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Paquetes creados"));

        tabla_paquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Código", "Descripción", "Cantidad de Libros"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_paquetes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_paquetes.getTableHeader().setReorderingAllowed(false);
        tabla_paquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_paquetesMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_paquetes);

        jLabel6.setText("Filtrar por:");

        filtrar_por.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODO", "Código Libro", "Descripción", "Cantidad de Libros" }));

        jLabel7.setText("Valor:");

        valor_a_filtrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valor_a_filtrarKeyReleased(evt);
            }
        });

        editar_paquete.setText("Editar descripción");
        editar_paquete.setEnabled(false);
        editar_paquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_paqueteActionPerformed(evt);
            }
        });

        agregar_libro_a_paquete.setText("Agregar Libro");
        agregar_libro_a_paquete.setEnabled(false);
        agregar_libro_a_paquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_libro_a_paqueteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filtrar_por, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor_a_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editar_paquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregar_libro_a_paquete)
                .addGap(53, 53, 53))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(filtrar_por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(valor_a_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editar_paquete)
                    .addComponent(agregar_libro_a_paquete)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de los Libros"));

        tabla_detalle_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Código", "Nombre", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabla_detalle_libros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        panel_descripcion_paquete.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Paquete seleccionado"));

        jLabel8.setText("Código:");

        codigo_paquete.setEditable(false);

        jLabel10.setText("Descripción:");

        descripcion_paquete.setColumns(20);
        descripcion_paquete.setRows(5);
        jScrollPane1.setViewportView(descripcion_paquete);

        guardar_descripcion_de_paquete.setText("Editar");
        guardar_descripcion_de_paquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_descripcion_de_paqueteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_descripcion_paqueteLayout = new javax.swing.GroupLayout(panel_descripcion_paquete);
        panel_descripcion_paquete.setLayout(panel_descripcion_paqueteLayout);
        panel_descripcion_paqueteLayout.setHorizontalGroup(
            panel_descripcion_paqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_descripcion_paqueteLayout.createSequentialGroup()
                .addGroup(panel_descripcion_paqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_descripcion_paqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panel_descripcion_paqueteLayout.createSequentialGroup()
                        .addComponent(codigo_paquete, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardar_descripcion_de_paquete))))
        );
        panel_descripcion_paqueteLayout.setVerticalGroup(
            panel_descripcion_paqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_descripcion_paqueteLayout.createSequentialGroup()
                .addGroup(panel_descripcion_paqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_descripcion_paqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(codigo_paquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(guardar_descripcion_de_paquete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_descripcion_paqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        panel_nuevo_libro.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar nuevo Libro"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código:");

        codigo_libro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_libroKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setText("Autor:");

        jLabel4.setText("Editorial:");

        jLabel5.setText("Estado:");

        estado_libro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excelente", "Bueno", "Medio", "Malo", "Muy malo" }));

        agregar_libro.setText("Agregar libro");
        agregar_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_libroActionPerformed(evt);
            }
        });

        cancelar_edicion_libro.setText("Cancelar");
        cancelar_edicion_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_edicion_libroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Los campos en negrita son obligatorios");

        javax.swing.GroupLayout panel_nuevo_libroLayout = new javax.swing.GroupLayout(panel_nuevo_libro);
        panel_nuevo_libro.setLayout(panel_nuevo_libroLayout);
        panel_nuevo_libroLayout.setHorizontalGroup(
            panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nuevo_libroLayout.createSequentialGroup()
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_nuevo_libroLayout.createSequentialGroup()
                        .addComponent(agregar_libro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar_edicion_libro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_nuevo_libroLayout.createSequentialGroup()
                        .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estado_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(editorial_libro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                .addComponent(autor_libro, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 63, Short.MAX_VALUE))))
            .addGroup(panel_nuevo_libroLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_nuevo_libroLayout.setVerticalGroup(
            panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nuevo_libroLayout.createSequentialGroup()
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(autor_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editorial_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(estado_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_nuevo_libroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_libro)
                    .addComponent(cancelar_edicion_libro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_nuevo_libro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_descripcion_paquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(regresar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_descripcion_paquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_nuevo_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor_a_filtrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valor_a_filtrarKeyReleased
        String valor = valor_a_filtrar.getText();
        if (valor.length() != 0) {
            int filtro = filtrar_por.getSelectedIndex();    // Obtengo el tipo de filtro en el que se basará la búsqueda
            // Si filtro==0 se buscará cualquier coincidencia (Código, Nombre, ...). En caso contrario, se busca en la columna 'filtro'
            if (filtro == 0)
                filtroTabla.setRowFilter(RowFilter.regexFilter(valor_a_filtrar.getText()));
            else
                filtroTabla.setRowFilter(RowFilter.regexFilter(valor_a_filtrar.getText(), filtro));
            tabla_paquetes.setRowSorter(filtroTabla);
            if (editar_paquete.isEnabled()) {  // Al filtrar las filas, se pierde la última fila seleccionada
                editar_paquete.setEnabled(false);
                agregar_libro_a_paquete.setEnabled(false);
            }
        }
    }//GEN-LAST:event_valor_a_filtrarKeyReleased

    private void tabla_paquetesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_paquetesMousePressed
        // Obtengo el listado de Libros del Paquete seleccionado
        obtener_libros_de_paquete(filtroTabla.convertRowIndexToModel(tabla_paquetes.getSelectedRow()));
        if (!editar_paquete.isEnabled()) {
            editar_paquete.setEnabled(true);
            agregar_libro_a_paquete.setEnabled(true);
        }
    }//GEN-LAST:event_tabla_paquetesMousePressed

    private void editar_paqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_paqueteActionPerformed
        indexPaqueteEditado = filtroTabla.convertRowIndexToModel(tabla_paquetes.getSelectedRow());
        DefaultTableModel modelPaquetes = (DefaultTableModel)tabla_paquetes.getModel();
        codigo_paquete.setText(modelPaquetes.getValueAt(indexPaqueteEditado, 1).toString());
        descripcion_paquete.setText("<Sin especificar>".equals(modelPaquetes.getValueAt(indexPaqueteEditado, 2).toString()) ? "" : modelPaquetes.getValueAt(indexPaqueteEditado, 2).toString());
        panel_descripcion_paquete.setVisible(true);
        tabla_paquetes.setEnabled(false);   // Para evitar que se seleccione otro registro
        editar_paquete.setEnabled(false);
        agregar_libro_a_paquete.setEnabled(false);
    }//GEN-LAST:event_editar_paqueteActionPerformed

    private void guardar_descripcion_de_paqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_descripcion_de_paqueteActionPerformed
        String descripcion = descripcion_paquete.getText();
        try {
            // Actualización del registro en la Base de Datos y en la Tabla
            conexion.prepareStatement("UPDATE PaqueteLibro SET"
                    + " Descripcion = "+(descripcion.length()==0 ? "NULL" : "'"+descripcion+"'")+" WHERE Id = "+listaIDPaquetes.get(indexPaqueteEditado)).executeUpdate();
            ((DefaultTableModel)tabla_paquetes.getModel()).setValueAt(descripcion.length()==0 ? "<Sin especificar>" : descripcion, indexPaqueteEditado, 2);
            codigo_paquete.setText("");     // Limpieza de campos
            descripcion_paquete.setText("");
            panel_descripcion_paquete.setVisible(false);
            tabla_paquetes.setEnabled(true);   // Habilitación de los componentes de visualización de Paquetes
            tabla_paquetes.removeRowSelectionInterval(0, tabla_paquetes.getRowCount()-1);
            obtener_libros_de_paquete(-1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se puede actualizar los datos del Paquete.\n\nDescripción:\n"+ex.getMessage(), "Error en conexión", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VerListadoPaquetes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardar_descripcion_de_paqueteActionPerformed

    private void agregar_libro_a_paqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_libro_a_paqueteActionPerformed
        indexPaqueteEditado = filtroTabla.convertRowIndexToModel(tabla_paquetes.getSelectedRow());
        panel_nuevo_libro.setVisible(true);
        tabla_paquetes.setEnabled(false);   // Para evitar que se seleccione otro registro
        editar_paquete.setEnabled(false);
        agregar_libro_a_paquete.setEnabled(false);
    }//GEN-LAST:event_agregar_libro_a_paqueteActionPerformed

    private void codigo_libroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_libroKeyTyped
        if (codigo_libro.getText().length() == 5)
            evt.consume();
    }//GEN-LAST:event_codigo_libroKeyTyped

    private void agregar_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_libroActionPerformed
        // Previo a agregar un libro, verifico que no exista otro en la tabla o en la Base de Datos con el mismo Código
        try {
            validar_datos_libro();  // Comprobación de que los datos sean correctos y que no se repitan
            // Creación del registro del nuevo Libro en la Base de Datos
            conexion.prepareStatement("INSERT INTO Libro(Codigo, Nombre, Autor, Editorial, Estado, PaqueteLibro_Id) VALUES("
                    + "'"+codigo_libro.getText()+"', "
                    + "'"+nombre_libro.getText()+"', "
                    + (autor_libro.getText().length()==0 ? "NULL" : "'"+autor_libro.getText()+"'")+", "
                    + (editorial_libro.getText().length()==0 ? "NULL" : "'"+editorial_libro.getText()+"'")+", "
                    + "'"+(estado_libro.getSelectedIndex()+1)+"', "
                    + listaIDPaquetes.get(indexPaqueteEditado)+")").executeUpdate();
            // Aumento el contador de libros del paquete seleccionado
            DefaultTableModel modelPaquetes = (DefaultTableModel)tabla_paquetes.getModel();
            modelPaquetes.setValueAt(""+(Integer.parseInt(modelPaquetes.getValueAt(indexPaqueteEditado, 3).toString())+1), indexPaqueteEditado, 3);
            JOptionPane.showMessageDialog(this, "El Libro fue agregado al Paquete No. "+(indexPaqueteEditado+1)+" con éxito", "Agregar libro", JOptionPane.INFORMATION_MESSAGE);
            limpiar_campos_libro();     // Limpio los componentes de entrada de datos, y de muestra de datos
            obtener_libros_de_paquete(-1);
            panel_nuevo_libro.setVisible(false);
            tabla_paquetes.setEnabled(false);   // Habilito los componentes para permitir la selección de otro Paquete
            tabla_paquetes.removeRowSelectionInterval(0, tabla_paquetes.getRowCount()-1);
        } catch (ExcepcionDatosIncorrectos ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en datos", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(CrearPaqueteLibro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se puede crear el registro del nuevo Libro.\n\nDescripción:\n"+ex.getMessage(), "Error en conexión", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VerListadoPaquetes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_agregar_libroActionPerformed

    private void cancelar_edicion_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_edicion_libroActionPerformed
        limpiar_campos_libro(); // Limpio los campos
        panel_nuevo_libro.setVisible(false);
        tabla_paquetes.setEnabled(true);    // Habilito los componentes para operar los Paquetes
        editar_paquete.setEnabled(true);
        agregar_libro_a_paquete.setEnabled(true);
    }//GEN-LAST:event_cancelar_edicion_libroActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    public boolean getHacerVisible() { return hacerVisible; }
    private void obtener_libros_de_paquete(int indexPaquete) {
        if (indexPaquete == -1)   // Borrar campos
            ((DefaultTableModel)tabla_detalle_libros.getModel()).setRowCount(0);
        else {
            try {
                Statement sentencia = conexion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
                ResultSet cConsulta = sentencia.executeQuery("SELECT Codigo, Nombre, Estado FROM Libro "
                        + "WHERE PaqueteLibro_Id = "+listaIDPaquetes.get(indexPaquete)+" AND Estado != '6' "
                        + "ORDER BY Nombre");
                DefaultTableModel modelLibros = (DefaultTableModel)tabla_detalle_libros.getModel();
                ArrayList<String> estados = new ArrayList<>();
                int contador = estado_libro.getItemCount();
                for(int i=0; i<contador; i++)
                    estados.add(estado_libro.getItemAt(i));
                contador = 0;
                while(cConsulta.next())
                    modelLibros.addRow(new String[]{
                        ""+(++contador),
                        cConsulta.getString("Codigo"),
                        cConsulta.getString("Nombre"),
                        estados.get(cConsulta.getInt("Estado")-1)
                    });
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "No se puede extraer alguno de los registros de Libros.\n\nDescripción:\n"+ex.getMessage(), "Error en conexión", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(VerListadoPaquetes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void validar_datos_libro() throws ExcepcionDatosIncorrectos {
        // Todos los Libros que se muestran se obtienen de la Base de Datos (no hay temporales)
        String codigoLibro = codigo_libro.getText();
        if (codigoLibro.length() == 0)
            throw new ExcepcionDatosIncorrectos("No ha especificado el Código del Libro");
        if (codigoLibro.length() != 5)
            throw new ExcepcionDatosIncorrectos("El Código del Libro debe tener 5 caracteres");
        if (nombre_libro.getText().length() == 0)
            throw new ExcepcionDatosIncorrectos("No ha especificado el Nombre del Libro");
        // Los otros campos no son obligatorios
        try {   // Verificación de que no exista otro Libro con el mismo Código en la Base de Datos
            ResultSet cConsulta = conexion.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY)
                    .executeQuery("SELECT Nombre, Autor, Editorial FROM Libro WHERE Codigo = '"+codigoLibro+"'");
            if (cConsulta.next())
                throw new ExcepcionDatosIncorrectos("Ya se registró un Libro con el mismo Código:"
                        + "\nCódigo:     "+codigoLibro
                        + "\nNombre:     "+cConsulta.getString("Nombre")
                        + "\nAutor:      "+(cConsulta.getString("Autor")==null ? "<No especificado>" : cConsulta.getString("Autor"))
                        + "\nEditorial:  "+(cConsulta.getString("Editorial")==null ? "<No especificado>" : cConsulta.getString("Editorial"))
                        + "\n\nNo se puede agregar el nuevo libro.");
        } catch (SQLException ex) { // Si ocurre un error, se asume que posiblemente ya exista el libro
            Logger.getLogger(VerListadoPaquetes.class.getName()).log(Level.SEVERE, null, ex);
            throw new ExcepcionDatosIncorrectos("Error al comprobar existencia del Libro.\n\nDescripción:\n"+ex.getMessage());
        }
    }
    private void limpiar_campos_libro() {
        codigo_libro.setText("");
        nombre_libro.setText("");
        autor_libro.setText("");
        editorial_libro.setText("");
        estado_libro.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerListadoPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerListadoPaquetes dialog = new VerListadoPaquetes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_libro;
    private javax.swing.JButton agregar_libro_a_paquete;
    private javax.swing.JTextField autor_libro;
    private javax.swing.JButton cancelar_edicion_libro;
    private javax.swing.JTextField codigo_libro;
    private javax.swing.JTextField codigo_paquete;
    private javax.swing.JTextArea descripcion_paquete;
    private javax.swing.JButton editar_paquete;
    private javax.swing.JTextField editorial_libro;
    private javax.swing.JComboBox<String> estado_libro;
    private javax.swing.JComboBox<String> filtrar_por;
    private javax.swing.JButton guardar_descripcion_de_paquete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nombre_libro;
    private javax.swing.JPanel panel_descripcion_paquete;
    private javax.swing.JPanel panel_nuevo_libro;
    private javax.swing.JButton regresar;
    private javax.swing.JTable tabla_detalle_libros;
    private javax.swing.JTable tabla_paquetes;
    private javax.swing.JTextField valor_a_filtrar;
    // End of variables declaration//GEN-END:variables
}
